# Generated by Django 5.1.7 on 2025-04-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Continents',
            },
        ),
        migrations.CreateModel(
            name='Passport_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Passports_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('image', models.URLField(max_length=500)),
                ('Continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='passport.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
