# Generated by Django 5.1.7 on 2025-04-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_passport_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Passport_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Passport_types', to='passport.passport_type'),
            preserve_default=False,
        ),
    ]
