# Generated by Django 5.1.7 on 2025-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_country_passport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='Passport_type',
        ),
        migrations.AddField(
            model_name='country',
            name='Passport_types',
            field=models.ManyToManyField(related_name='Countries', to='passport.passport_type'),
        ),
    ]
