# Generated by Django 5.1.7 on 2025-04-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_remove_country_passport_type_country_passport_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Passport_types',
            new_name='Passport_type',
        ),
    ]
