# Generated by Django 5.1.7 on 2025-05-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_rename_passport_types_country_passport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
    ]
